$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
model: azureml:risk-model:1
code_configuration:      
  code: 
    local_path: scoring/
  scoring_script: score.py    
environment: 
  conda_file: environment/conda.yml
  docker:
    image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20210727.v1
instance_type: Standard_F2s_v2
instance_count: 1