name: saferollout
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - azure-mgmt-monitor==2.0.0
    - azure-identity==1.5.0
    - vcrpy==4.1.1
    - tabulate==0.8.9
