name: setup
on: 
  workflow_dispatch

env:
  TRAINING_CLUSTER: cpu-cluster # this name is used in train/job.yaml as well

jobs:  
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - run: |
          az config set defaults.workspace=${{secrets.AML_WORKSPACE}}
          az config set defaults.group=${{secrets.RESOURCE_GROUP}}          
          az account set -s ${{secrets.SUBSCRIPTION_ID}}  
    - name: Install azureml cli extension
      run: az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.15_october_cand-py3-none-any.whl --yes
      #run: az extension add -n ml -y
    - name: Create azureml workspace if it does not exist
      run: az ml workspace create -n ${{secrets.AML_WORKSPACE}} --location ${{secrets.LOCATION}}
      continue-on-error: true
    - name: "Create Log Analytics workspace (if it does not exist)"
      run: az monitor log-analytics workspace create --workspace-name ${{secrets.LA_WORKSPACE}} --location ${{secrets.LA_LOCATION}} --retention-time 730  --sku pergb2018 
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Create dataset
      run: az ml dataset create -n credit-dataset -l dataset/german_credit_data.csv
    - name: Create training cluster
      run: az ml compute create -n ${{ env.TRAINING_CLUSTER }} --type amlcompute --min-instances 0 --max-instances 5
